### ISSUE TITLE
Hey! You leaked your bearer token :) 

### ISSUE THREAD

**Issue by oracularhades** [ilyasderaiya/food#1]
https://github.com/ilyasderaiya/food/blob/6cddcfc2dd71c7948285b346d8f233a1eb2d7ae1/src/api/yelp.js

Line: 7.

**Comment by ilyasderaiya** [comment]
I am new to react and don't know how to hide it.

**Comment by oracularhades** [comment]
Set it to another file and have Github ignore that file when uploading :)

Make the file something like "keys.json", then when React needs the key go in there and fetch it pragmatically via the JSON API.

Then, add that file to your .gitignore file.

**Comment by oracularhades** [comment]
You need to deactivate that bearer token now, by this point someone has probably taken it and used it. Check there isn't any damage.

**Comment by oracularhades** [comment]
BTW - your API tokens SHOULD NEVER be in the frontend, store your API tokens in the backend, otherwise anyone can get them.
